{
  "hash": "602e8e8cec684c05b5b543d658cdd9b2",
  "result": {
    "engine": "knitr",
    "markdown": "# Summary Statistics\n\nWe've given a few examples of ways to visualize data, now we want to talk about some important **summary statistics**. Summary statistics are quantitative values one can use help describe the shape of a distribution. We will talk about measures of **center** and measures of **spread**.\n\nAlmost always, summary statistics can only be used on *quantitative data*. \n\n## Measures of Center\n\nThe goal of measures of *center* is to describe the value of a typical datapoint. There are three measures of center we will cover:\n\n* **Mode**: The value(s) with the highest frequency in the dataset. Mode is the *only* measure of center that can be used with categorical data. \n* **Mean**: The average of the values. If a dataset has $n$ values $x_1$, $x_2$, $\\dots$, $x_n$, then the mean $\\bar{x}$ is given by \n\n$$\\bar{x} = \\frac{x_1+x_2+ \\cdots + x_n}{n}.$$\n\n* **Median**: The midpoint of the distribution. It is the number such that half the observations fall above and half fall below. \n\n::: {#exm-ages}\n## Classroom Ages\nA college class has 22 students with the following ages: 18, 22, 21, 21, 21, 18, 20, 42, 23, 44, 18, 18, 21, 18, 22, 18, 22, 23, 20, 38, 20, 34. Compute the mean, median, and mode. \n\n[See this data on StatCrunch to perform the computations there.](https://www.statcrunch.com/app/index.html?dataid=5133686){target=\"_blank\"}\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Answer \nTo compute the mode and median it helps to order the data from smallest to largest. \n\n$$18, 18, 18, 18, 18, 18, 20, 20, 20, 21, 21, 21, 21, 22, 22, 22, 23, 23, 34, 38, 42, 44$$\n\nThe mode is 18, which occurs in the dataset 6 times. \n\nSince the dataset is 22 students, the median is the value in-between the 11th and 12th observations. The 11th and 12th observation both happen to be 21, therefore the median is 21.\n\nThe mean is,\n\n$$\\frac{6 \\cdot 18 + 3 \\cdot 20 + 4 \\cdot 21 + 3 \\cdot 22 + 2 \\cdot 23  + 34 + 42 + 44}{22} = \\frac{522}{22} = 23.73.$$\n\nNotice that the mean is slightly larger than the median this is because there are a handful of older students with *outlier* ages. The mean gets pulled by outliers more than the median does.\n:::\n\n::: {.callout-important title=\"Median on Datasets of Even Size\"}\nFor this course, to compute the median when the dataset has an *even* number of observations average the two observation in the middle. This is a typical convention chosen in statistics. \n:::\n\nThe difference between the median and mean of a distribution can reveal information about the shape of the distribution. In particular, if a distribution is **skewed** or **symmetric**. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Right-skewed household income distribution.](lecture-02_files/figure-html/fig-income-1.png){#fig-income width=576}\n:::\n:::\n\n\nWhen a distribution is skewed, the mean is pulled more towards the **tail** than the median. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Approximately symmetric distribution of soccer team heights.](lecture-02_files/figure-html/fig-heights-1.png){#fig-heights width=576}\n:::\n:::\n\n\n::: {.callout-important title=\"Mean Versus Median\"}\nThe reason **outliers pull the mean more than the median** is because mean minimizes the error *squared*, while the median minimizes the absolute error. Squaring the error means outliers will have extra impact. This fact is outside of the scope of this course, but I am happy to chat about it for curious minds!\n:::\n\n::: {#exm-createdata1}\n## Creating Data\nUsing StatCrunch complete the following:\n\n1. Create a dataset of 10 student ages where the median is 20 and at least one student is not 20.\n\n2. Is it possible to do this and have no student be 20 years old? \n\n3. If we increased the size of the dataset to 15 students can you still create a dataset with median 20 *and* no students are 20 years old?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\n\n1. One possible answer: 18, 18, 18, 19, 20, 20, 20, 21, 22, 23.\n\n2. Yes it is! Since the dataset has an *even* size, we can make it so the 5th entry is 19 and the 6th entry is 21. Such as: 18, 18, 18, 19, 19, 21, 22, 23, 25.\n\n3. This is **not** possible if the dataset has an *odd* size. When there are 15 students, the age of the 8th youngest student is the median--so that student must be 20. \n:::\n\n::: {#exm-createdata2}\n1. Using StatCrunch or Google Sheets, create a dataset of 25 non-negative integers (e.g. whole numbers 0 and larger) where the mean is less than the median. Plot the histogram of the data. \n\n2. (Challenge) If I have a dataset of 25 **non-negative integers** and the median is 50, what is the smallest possible mean?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\n1. Your dataset should be **skewed to the left** in this example. \n\n2. The smallest possible mean occurs when 12 data points have value 0 and 13 have the value 50. This guarantees the median is 50. So the mean is \n\n$$\\frac{12 \\cdot 0 + 13 \\cdot 50}{25} = 26.$$\n\nWe can't make any of numbers smaller or else we would either change the median or break the non-negative rule. Making any of the numbers bigger would increase the mean! \n::: \n\n::: {.callout-important title=\"When to use mode?\"}\nDiscuss: what might be a situation where the mode is the most relevant summary statistic to use?\n:::\n\n::: {.callout-tip collapse=\"true\"}\nMode is the only measure of center that can be used for categorical data. Also, mode is great for bimodal (or multimodal) distributions!\n:::\n\n::: {.callout-important title=\"Nobody's Average\"}\nIn 1950 the airforce measured 140 physical dimension of 4063 pilots and designed the cockpit to match he average (mean) dimensions. Lieutenant Gilbert S. Daniels then compared this \"average pilot\" to individual pilot records to show that no pilot was within 15% of the average on the ten most relevant dimensions. In other words, the cockpits were designed to fit no one! Thus lead to the adaptation of adjustable seats. \n:::\n\n## Measures of Spread\n\n::: {#exm-spreaddiff}\n## Commute Times\n[Data on StatCrunch.](https://www.statcrunch.com/app/index.html?dataid=5133808){target=\"_blank\"} The below histograms depict the commute time of 500 people who work in Town A and Town B. How are the datasets similar and how are they different?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Commute times in two different towns.](lecture-02_files/figure-html/fig-commute-spread-1.png){#fig-commute-spread width=864}\n:::\n:::\n\n:::\n\nThe above example illustrates that it is important to have statistics that describe the *spread* of a distribution. There are a few we will investigate today.\n\n### Range\n\nThe **range** of a dataset is the largest observation minus the smallest observation. \n\n\n::: {.cell}\n\n:::\n\n\n::: {#exm-commutetimes}\n[The commute times data is given here.](https://www.statcrunch.com/app/index.html?dataid=5133808){target=\"_blank\"} Compute the range of the commuting data for each town. \n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\nFor Town A, the longest and shortest commute times are 42 and 18 minutes, respectively. So the range for Town A is $42-18 = 24$.\n\nFor Town B, the longest and shortest commute times are 62 and 1 minute, respectively. So the range for Town B is $62-1 = 61$. \n:::\n\nRange does give us an initial look at the spread of the distribution, but **outliers** can obfuscate how range relates to spread. Consider two classes with the following histograms of exam scores:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Scores on Exam 1 in Class A and Class B](lecture-02_files/figure-html/fig-quiz-spread-1.png){#fig-quiz-spread width=864}\n:::\n:::\n\n\nThe range of both distributions is (approximately) the same, but the spread looks very different. Only 2 out of 20 students scored below a 60 in Class A, while 8 students (out of 20) scored below a 60 in Class B. \n\n### Inter-Quartile Range (IQR)\n\nRecall that the **median** divides the observations into two parts of equal size. This is because we defined the median as the value which half the observations are below and half are above. **Quartiles** divide the data into 4 equal parts. Specifically we define:\n\n* The first quartile (or lower quartile), Q1, is the value such that 25% of the data lies below this value. \n* The second quartile (or median), M, is value where 50% of the data lies below this value. \n* The third quartile (or upper quartile), Q3, is the value such that 75% of the data lies below this value. \n\nComputing the min, Q1, Q2, Q3, and max of a data set is known as the **five-number summary**. \n\n::: {.callout-important}\nNote that Q1 and Q3 are computed differently on Google Sheets than on StatCrunch (and in this class). While they are effectively the same, it will sometimes cause incorrect homework answers. \n:::\n\n::: {#exm-5num}\nBelow are the exact list of Exam 1 scores for Class A and Class B (from the histograms in Figure @fig-quiz-spread).  Compute the five-number summary for each class. What differences do you observe about the distribution from the statistics?\n\n| Class A | Class B | Position Number |\n|---------|---------|-----------------|\n| 10      | 10      | 1 | \n| 44      | 34      | 2 |\n| 66      | 36      | 3 |\n| 70      | 44      | 4 |\n| 71      | 45      | 5 |\n| 73      | 48      | 6 |\n| 74      | 50      | 7 |\n| 76      | 56      | 8 |\n| 77      | 64      | 9 |\n| 79      | 66      | 10 |\n| 80      | 76      | 11 |\n| 80      | 77      | 12 |\n| 80      | 80      | 13 |\n| 82      | 82      | 14 |\n| 83      | 83      | 15 |\n| 83      | 84      | 16 |\n| 86      | 88      | 17 |\n| 87      | 89      | 18 |\n| 91      | 91      | 19 |\n| 96      | 95      | 20 |\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Answer \nEach class list is already ordered for us, so we have:\n\n* Min = 1st grade --> Class A = 10, Class B = 10\n* Q1 = between 5th and 6th grade --> Class A = 72, Class B = 46.5\n* M = between 10th and 11th grade --> Class A = 79.5, Class B = 71\n* Q3 = between 15th and 16th grade --> Class A = 83, Class B = 83.5\n* Max = 20th grade --> Class A = 96, Class B = 95\n:::\n\nThe **inter-quartile range** (IQR) is defined as Q3-Q1. \n\n::: {#exm-iqr}\nCompute the IQR for the exam scores by class. \n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\nFor Class A, IQR = Q3 - Q1 = 83 - 72 = 11. For Class B, IQR = 83.5 - 46.5 = 47.\n:::\n\n::: {.callout-important title=\"IQR Versus Range\"}\nWhy might IQR be seen as a better gauge of spread than range? \n:::\n\n### Outliers\n\nAn **outlier** is an oberservation that lies far away from the general distribution. The readings define outliers as points that are:\n\n* Smaller than $\\text{Q}1 - 1.5 \\cdot (\\text{IQR})$, or \n* Larger than $\\text{Q}3 + 1.5 \\cdot (\\text{IQR})$.\n\n<span style=\"color:red;\">**Do not**</span> think of this as a set in stone rule. In fact, the multiplier 1.5 was not chosen with any real mathematical theory behind it. Use these values to flag *potential* outliers in the dataset, but context is an important factor when determining what is an outlier. Moreover, <span style=\"color:red;\">**do not**</span> automatically remove outliers from a dataset \n\n::: {#exm-commutebimodal}\n## Bimodal Commute Times\nWe have the following list of commute times for a neighborhood: \n\n--  --  --  --  --  --\n24  25  26  27  27  28\n28  29  29  30  30  30\n31  31  32  32  33  33\n34  34  35  35  36  36\n37  38  39  40  41  42\n72  74  76  78  80  82\n--  --  --  --  --  --\n\nLet's start by looking at the five-number summary.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.0 29.5 33.5 39.5 82.0\n```\n\n\n:::\n:::\n\n\nFrom this we can compute the lower and upper fence:\n\n$$\\text{lower} = 29.5 - 1.5(10) = 14.5, \\quad \\text{upper} = 39.5 + 15 = 54.5$$\n\nThat means 6 data points are flagged as outliers using this rule: 72, 74, 76, 78, 80, 82. Let's look at the histogram of the distribution, \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Histogram of neighborhood commute times.](lecture-02_files/figure-html/fig-bimodal-commute-1.png){#fig-bimodal-commute width=576}\n:::\n:::\n\n\nWhat we see from the histogram is a **bimodal** distribution. There is one subset of the neighborhood that commutes a shorter distance (think across town), while a small subset of the neighborhood commutes to a different city. This is an example where the $1.5 \\times \\text{IQR}$ rule is a bad fit.\n:::\n\n::: {.callout-important title=\"Removing Data\"}\nThere is a false notion that outliers should be removed from the data set but this is **not true**! Outliers should be expected in data and are part of the underlying distribution. \n\nOnly remove data points if they are the result of mistake in data entry or collection, or if they can be explained by a fundamentally different process which you are not interested in investigating. \n:::\n\n## Boxplots\n\n**Boxplots** are a way to visualize the five number summary as well as outliers. Let's see this with an example.\n\n::: {#exm-boxplot}\n## Boxplots in StatCrunch\n[For this example use this data on StatCrunch.](https://www.statcrunch.com/app/index.html?dataid=5141492){target=\"_blank\"} To make a boxplot of the data select Graph > Boxplot. Just select annual_income and then compute. \n:::\n\nThe box of the boxplot goes from Q1 to Q3 and the median is shown as a horizontal line. The two sticks (called whiskers) on either side of the box go until the largest data point *that isn't an outlier* and the stars (called fences) indicate outlier values. If we deselect the box indicating \"Use fences to identify outliers\" in StatCrunch then the whiskers will go all the way until the end of the range. \n\n![Labeled boxplot.](images/boxplot_def.png){fig-align=\"center\"}\n\n::: {#exm-boxplotcompare}\nThe boxplots below show the typed words per minutes for support agents and software engineers. Compare the two distributions using what you know about boxplots. \n\n![Typing speed boxplots for support agents and software engineers.](images/wpm_boxplot.png){fig-align=\"center\"}\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\nThe median support agent is a faster typer than the median software engineer. Software engineers have a much larger *variation* in typing speeds then support agents. \n:::\n\n## Standard Deviation\n\nHere we will define and use the **sample standard deviation**. This is slightly different, but related to, the *population* standard deviation as well as the variance. These are terms we will define explicitly later. Given data points $x_1$, \\dots, $x_n$ the **sample standard deviation** is defined by the formula\n\n$$SD = \\sqrt{\\frac{(x_1-\\bar{x})^2 + (x_2-\\bar{x})^2 + \\cdots + (x_n - \\bar{x})^2}{n-1}}$$\n\nwhere $\\bar{x}$ denotes the mean of the dataset. Let's see this formula in action with a small example,\n\n::: {#exm-sdsmall}\nAnna denotes how many Reese's Peanutbutter Cups her 10 friends eat at a party. She gets the following amounts:\n\n$$3, 4, 3, 6, 6, 2, 1, 8, 5, 5.$$\n\nCompute the mean and standard deviation of the dataset. \n\n::: {.callout-tip collapse=\"true\"}\n## Answer \nLet's compute the mean,\n\n$$\\bar{x} = \\frac{3+4+3+6+6+2+1+8+5+5}{10} = \\frac{43}{10} = 4.3.$$\n\nNext compute the differences,\n\n$$-1.3,-0.3,-1.3,1.7,1.7,-2.3,-3.3,3.7,0.7,0.7.$$\n\nSquare and sum, \n\n$$ 1.69 + 0.09 + 1.69 + 2.89 + 2.89 + 5.29 + 10.89 + 13.69 + 0.49 + 0.49 = 40.1 $$\n\nNow divide by $n-1 = 10-1 = 9$ and take the square root,\n\n$$SD = \\sqrt{\\frac{40.1}{9}} = \\sqrt{4.456} \\approx 2.11.$$\n:::\n\nWe claim that standard deviation is telling us *something* about the spread of the distribution, but we can be more precise than that. The standard deviation tell us the average distance from an given datapoint to the mean. A larger standard deviation means the data is more spread out, while a smaller standard deviation tells us the data is compact.\n\n::: {#exm-sd}\n## Standard Deviation in StatCrunch\n[For this example use this data on StatCrunch.](https://www.statcrunch.com/app/index.html?dataid=5141492){target=\"_blank\"} Compute the standard deviation of the income dataset. \n:::\n\n::: {#exm-varyingstd}\nWhich histogram has the smallest standard deviation? The largest?\n\n::: {.cell}\n::: {.cell-output-display}\n![Histograms of data with similar mean and different standard deviations.](lecture-02_files/figure-html/std-data-1.png){width=864}\n:::\n:::\n\n:::\n\n## Normal Distribution and the 68-95-99.7 \n\nQuantitative data is **normally** distributed when its distribution looks like a symmetric \"mound\" or \"bell\" shape. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Histogram of approximately normal data.](lecture-02_files/figure-html/normal-data-1.png){width=576}\n:::\n:::\n\n\nThings that are approximately normal in distribution include:\n\n* Baby birth weights\n* Heights of adults by sex\n* Blood pressure of adults\n* Standardized testing scores\n\nStatistics over time may have you thinking everything is normal, but this is not true! You should always question whether a distribution is normal or has some other distribution. Things that are *not* normal include:\n\n* Income\n* Time between earthquakes in a given region\n* Number of shots taken in a soccer game\n* Amount of time someone waits in a line\n\nIf a distribution is normal though, the **empirical rule** (or 68-95-99.7 rule) gives us a rough estimate of what percentage of the data falls withing 1, 2, and 3 standard deviations of the mean. We have:\n\n* 68% of the data falls within 1 standard deviation of the mean\n* 95% of the data falls within 2 standard deviations of the mean\n* 99.7% falls within 3 standard deviations of the mean\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lecture-02_files/figure-html/empirical-rule-1.png){width=576}\n:::\n:::\n\n\n::: {#exm-babywts}\n## Baby Weights\nThe mean birth weight at a hospital is 7.3 lbs with a standard deviation of 1.1 lbs. Assume that the birth weight is approximately normally distributed. \n\n1. What percentage of babies weigh between 6.2 lbs and 8.4 lbs?\n2. What percentage of babies weigh less than 4.0 lbs?\n:::\n\n## Extra Practice\n\n1. Compute the mean and median for the annual income dataset. Based on these values is the data skewed to thee right or left? Generate a histogram of the data to confirm your thoughts. [Data](https://www.statcrunch.com/app/index.html?dataid=5141492){target=\"_blank\"}\n\n2. A survey recorded the time spent on homework in two different grades. The five-number summaries are recorded below. Compute the IQR for each grade. What are the main differences in the distributions?\n\n| | Grade 9 | Grade 11 |\n| --- | --- | --- |\n| Minimum | 60 | 40 |\n| Q1 | 90 | 70 |\n| Median | 110 | 120 |\n| Q3 | 130 | 200 |\n| Maximum | 160 | 260 | \n\n3. The principal tells you that, based on the above sumamary data, 9th graders and 11th graders spend a similar amount of time on homework. How might you respond to the principal?\n\n4. The box plot shows commute times (in minutes) for 36 employees. \n\na) Estimate the median, Q1, and Q3. What is the IQR? \n\nb) Would the mean be larger or smaller than the median? Why?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lecture-02_files/figure-html/commute-box-1.png){width=576}\n:::\n:::\n\n\n5. A news article reports: \"The mean commute time is 25 minutes with a standard deviation of 40 minutes.\" What does this suggest about the shape of the distribution? Why might this statement be misleading?\n\n6. Heights of adult women in the U.S. are approximately normal, with a mean of 64 inches and a standard deviation of 2.5 inches.\n\na) What percentage of women are between 61.5 and 66.5 inches tall?\n\nb) What percentage of women are taller than 69 inches?\n\nc) What percentage of women are between 59 and 66.5 inches tall?",
    "supporting": [
      "lecture-02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}